In [1]:
import pandas as pd

In [2]:
stockprice = pd.read_csv('dataset/stockprice_abnormal_labeled.csv')
news = pd.read_csv('dataset/articles_w_published_dates.csv')

In [3]:
stockprice

                           Date        Close  label
0     2003-11-12 00:00:00+07:00    47.092968      1
1     2003-11-13 00:00:00+07:00    47.092968      0
2     2003-11-14 00:00:00+07:00    47.092968      0
3     2003-11-17 00:00:00+07:00    44.850452      1
4     2003-11-18 00:00:00+07:00    43.729198      0
...                         ...          ...    ...
5027  2024-08-06 00:00:00+07:00  4600.000000      0
5028  2024-08-07 00:00:00+07:00  4620.000000      0
5029  2024-08-08 00:00:00+07:00  4660.000000      0
5030  2024-08-09 00:00:00+07:00  4670.000000      0
5031  2024-08-12 00:00:00+07:00  4680.000000      0

[5032 rows x 3 columns]

In [4]:
news

,title,link,date_accessed,date_published,content
0,Dirut BRI Bicara Transformasi Digital dan Pemb...,https://finansial.bisnis.com/read/20230905/90/...,2024-08-05,2023-09-05T09:21:00+07:00,"Bisnis.com, JAKARTA - Direktur Utama PT Bank R..."
1,Dirut BRI Sunarso Bicara Transformasi Digital ...,https://bisnis.tempo.co/read/1768366/dirut-bri...,2024-08-05,2023-09-05T15:25:47+07:00,Lupa Kata Sandi? Klik di Sini atau Masuk melal...
2,"Bicara KUR, Dirut BRI Berdebat Keras dengan An...",https://www.demokrat.or.id/bicara-kur-dirut-br...,2024-08-05,2019-11-28T08:57:25+00:00,Jakarta: PT Bank Rakyat Indonesia (Persero) Tb...
3,Dirut BRI Buka Suara soal Usulan Jokowi Perpan...,https://economy.okezone.com/read/2024/07/25/32...,2024-08-05,2024-07-25T12:24:53+07:00,JAKARTA - Direktur Utama PT Bank Rakyat Indone...
4,Dirut BRI nilai perbankan perlu bentuk badan a...,https://www.antaranews.com/berita/4075392/diru...,2024-08-05,2024-04-25T21:15:42+07:00,Pewarta: Uyu Septiyati LimanEditor: Nusarina Y...
5,"Dorong Pelaku Usaha Bangkit, Dirut BRI Sunarso...",https://biz.kompas.com/read/2022/09/29/1252046...,2024-08-05,2022-09-29T05:52:04+00:00,"Dorong Pelaku Usaha Bangkit, Dirut BRI Sunarso..."
6,Cerita Sunarso Melakukan Transformasi di BRI,https://www.theiconomics.com/iconic-leader/cer...,2024-08-05,2023-10-26T12:59:49+00:00,© Copyright ICONOMICS. All Rights Reserved. Su...
7,Dirut BRI ungkap strategi jaga rasio NPL UMKM ...,https://www.antaranews.com/berita/4215419/diru...,2024-08-05,2024-07-25T12:10:02+07:00,Pewarta: Rizka KhaerunnisaEditor: Ahmad Buchor...
8,"Menurut Pengamat, Ini Tantangan Dirut Baru BRI",https://money.kompas.com/read/2019/09/02/19370...,2024-08-05,2019-09-02T12:37:00+00:00,"Menurut Pengamat, Ini Tantangan Dirut Baru BRI..."
9,"Kursi dirut Bank BRI kosong, Sunarso dan Hexan...",https://www.antaranews.com/berita/1036578/kurs...,2024-08-05,2019-08-30T10:38:58+07:00,Pewarta: Royke SinagaEditor: Faisal Yunianto\t...
10,Setelah Suprajarto: Tiga Direksi BRI Bakal Dic...,https://infobanknews.com/setelah-suprajarto-ti...,2024-08-05,2019-08-30T00:59:06+00:00,Suprajarto menyatakan mundur dari hasil RUPSLB...
11,Mantan Dirut BRI Temu Kangen: (1)Kepemimpinan ...,https://republiknews.co.id/mantan-dirut-bri-te...,2024-08-05,2024-05-12T23:40:13+08:00,Pengantar:Jumat (10/5/2024) pagi tiba-tiba mas...
12,Profil Sunarso: Dirut BRI Jadi Dirut BRI,https://serikatnews.com/profil-dirut-bri-sunarso/,2024-08-05,2019-09-02T13:50:45+00:00,AGRI 1577 (0) | BASIC-IND 938 (0) | ...
13,Profil Dirut Bank BRI,https://mediapasti.com/nasional/19577/profil-d...,2024-08-05,2024-07-29T09:18:23+00:00,Home / Nasional / Profil Dirut Bank BRI Mediap...
14,Mantan Dirut BRI Temu Kangen: (1)Kepemimpinan ...,https://republiknews.co.id/mantan-dirut-bri-te...,2024-08-05,2024-05-12T23:40:13+08:00,Pengantar:Jumat (10/5/2024) pagi tiba-tiba mas...
15,Profil Sunarso: Dirut BRI Jadi Dirut BRI,https://serikatnews.com/profil-dirut-bri-sunarso/,2024-08-05,2019-09-02T13:50:45+00:00,AGRI 1577 (0) | BASIC-IND 938 (0) | ...
16,BRI Resmi jadi Induk Holding BUMN Ultra Mikro,https://www.topbusiness.id/55374/bri-resmi-jad...,2024-08-05,2021-09-14T05:57:50+00:00,"Jakarta, TopBusiness – Holding Ultra Mikro ya..."
17,"""Bank Terbaik di Indonesia"" Versi The Asian Ba...",https://www.balipost.com/news/2021/06/23/19973...,2024-08-05,2021-06-23T09:13:20+00:00,"29.8 CDenpasar, BaliSenin, 5 Agustus 2024e..."
18,Dirut BRI Tanggapi soal Kredit Macet UMKM dan ...,https://finansial.bisnis.com/read/20240725/90/...,2024-08-05,2024-07-25T12:28:54+07:00,Nyaman tanpa iklan. Langganan BisnisPro Nyaman...
19,Kepemimpinan yang Kuat Jadi Kunci Keberhasilan...,https://ekonomi.republika.co.id/berita/s09c0t4...,2024-08-05,2023-08-31T20:26:53+07:00,Ada delapan hal yang dikedepankan BRI untuk di...
20,BRI Resmi Menjadi Induk Holding BUMN Ultra Mikro,https://sawitindonesia.com/bri-resmi-menjadi-i...,2024-08-05,2021-09-15T06:00:00+00:00,JAKARTA – Holding Ultra Mikro yang melibatkan ...
21,Profil Dirut Bank BRI,https://mediapasti.com/nasional/19577/profil-d...,2024-08-05,2024-07-29T09:18:23+00:00,Home / Nasional / Profil Dirut Bank BRI Mediap...
22,Perempuan 22 Tahun Asal NTT Jadi Dirut BRI Sel...,https://www.inews.id/finance/bisnis/perempuan-...,2024-08-05,2021-09-30T11:47:00+07:00,"Scan this QR or download app from: JAKARTA, iN..."
23,Perempuan 22 Tahun Asal NTT Jadi Dirut BRI Sel...,https://www.inews.id/finance/bisnis/perempuan-...,2024-08-05,2021-09-30T11:47:00+07:00,"Scan this QR or download app from: JAKARTA, iN..."
24,"Mantan Dirut BRI Rudjito Meninggal, Ini Kata D...",https://nasional.tempo.co/read/703574/mantan-d...,2024-08-05,2015-09-24T21:56:00+07:00,Lupa Kata Sandi? Klik di Sini atau Masuk melal...
25,"Tentang Suprajarto, Dirut BRI yang Tolak Jadi ...",https://www.viva.co.id/bisnis/1177197-tentang-...,2024-08-05,2019-08-30T07:25:31+07:00,"VIVA – Kamis malam kemarin, 29 Agustus 2019 da..."
26,Wamen BUMN Cerita Hasil Diskusi Bareng Dirut B...,https://www.liputan6.com/bisnis/read/5590718/w...,2024-08-05,2024-05-07T18:30:54+07:00,liputan6 Wakil Menteri Badan Usaha Milik Nega...
27,Dirut BRI Ungkap Strategi Jaga Rasio NPL UMKM ...,https://www.news-bank.net/dirut-bri-ungkap-str...,2024-08-05,2024-07-25T13:29:19+00:00,"Kita harus masih bertambah pada UMKM, tapi sa..."
28,Intip Potret Kebersamaan Direktur BRI Handayan...,https://www.cantika.com/read/1880513/intip-pot...,2024-08-05,2024-06-16T18:30:00+07:00,"\n\n\n\n\n Minggu, 16 Juni 2024 18:30 WIB Repo..."
29,"Pimpinan Bank BRI Unit Koto Tangah, Menuduh Di...",https://liputan7.id/antri-berjam-jam-eh-tak-ta...,2024-08-05,2022-05-09T18:52:43+07:00,"Koto Tangah,Liputan7.id – Pimpinan Bank BRI Un..."
30,BRI-MI Tunjuk Tina Meilina Sebagai Direktur Ut...,https://rakyatntt.com/bri-mi-tunjuk-tina-meili...,2024-08-05,2024-06-25T12:25:12+08:00,Tina Meilina resmi ditunjuk sebagai Direktur U...
31,BRI-MI Tunjuk Tina Meilina Sebagai Direktur Ut...,https://rakyatntt.com/bri-mi-tunjuk-tina-meili...,2024-08-05,2024-06-25T12:25:12+08:00,Tina Meilina resmi ditunjuk sebagai Direktur U...
32,Mantan Dirut BRI Suprajarto Meninggal Dunia di...,https://ekonomi.republika.co.id/berita/s5wht23...,2024-08-05,2023-12-19T13:24:38+07:00,Suprajarto menjabat sebagai Direktur Utama Ban...
33,Dirut Bank Syariah Indonesia Raih Gelar Doktor...,https://www.theiconomics.com/iconic-leader/dir...,2024-08-05,2021-07-29T12:52:32+00:00,© Copyright ICONOMICS. All Rights Reserved. Di...
34,"Rudjito, Bankir Profesional 'Penyelamat' BRI",https://economy.okezone.com/read/2016/07/29/32...,2024-08-05,2016-07-29T10:54:16+07:00,"JAKARTA - Bankir profesional, Rudjito, telah m..."
35,Suprajarto Tolak Ditetapkan Sebagai Dirut BTN,https://www.ngopibareng.id/read/suprajarto-tol...,2024-08-05,2019-08-29T23:00:48+07:00,Topik menarik Notifikasi Tidak ada notifika...
36,4 Potret Kedekatan Direktur Konsumer BRI Handa...,https://www.cantika.com/read/1850857/4-potret-...,2024-08-05,2024-03-29T12:00:00+07:00,"\n\n\n\n\n Jumat, 29 Maret 2024 12:00 WIB Repo..."
37,Indeks Bisnis UMKM BRI Triwulan II 2024,https://www.viva.co.id/bisnis/1737944-indeks-b...,2024-08-05,2024-08-01T10:55:27+07:00,VIVA – PT. Bank Rakyat Indonesia (Persero) Tbk...
38,"Sambut Positif Sinergi dengan MNC Bank, Dirut ...",https://www.inews.id/finance/bisnis/sambut-pos...,2024-08-05,2024-08-01T21:11:00+07:00,"Scan this QR or download app from: JAKARTA, iN..."
39,LinkAja Luncurkan Aplikasi Layanan Pembayaran ...,https://bumntrack.co.id/linkaja-luncurkan-apli...,2024-08-05,2023-09-05T08:35:20+07:00,"Jakarta, BUMN TRACK – Sebagai bagian dari foku..."
40,Mantan Dirut BRI Suprajarto Wafat,https://aspek.id/mantan-dirut-bri-suprajarto-w...,2024-08-05,2023-12-19T03:29:35+00:00,"Eks Direktur Utama (Dirut) BRI, Suprajarto, m..."

In [5]:
news['date_published'] = pd.to_datetime(news['date_published'], utc=True).dt.tz_convert('Asia/Jakarta').dt.date
stockprice['Date'] = pd.to_datetime(stockprice['Date']).dt.date

In [6]:
df = pd.merge(stockprice, 
              news.drop(columns=['date_accessed', 'link', 'title']), 
              left_on='Date', right_on='date_published', how='inner')
df.drop('date_published', axis=1, inplace=True)
df.drop_duplicates(subset=['content'], inplace=True)

In [7]:
df

,Date,Close,label,content
0,2016-07-29,1533.742432,0,"JAKARTA - Bankir profesional, Rudjito, telah m..."
1,2019-08-29,3082.552490,0,Topik menarik Notifikasi Tidak ada notifika...
2,2019-08-30,3133.928711,0,Pewarta: Royke SinagaEditor: Faisal Yunianto\t...
3,2019-08-30,3133.928711,0,Suprajarto menyatakan mundur dari hasil RUPSLB...
4,2019-08-30,3133.928711,0,"VIVA – Kamis malam kemarin, 29 Agustus 2019 da..."
5,2019-09-02,3097.231445,0,"Menurut Pengamat, Ini Tantangan Dirut Baru BRI..."
6,2019-09-02,3097.231445,0,AGRI 1577 (0) | BASIC-IND 938 (0) | ...
8,2019-11-28,2972.461426,0,Jakarta: PT Bank Rakyat Indonesia (Persero) Tb...
9,2021-06-23,3076.993652,0,"29.8 CDenpasar, BaliSenin, 5 Agustus 2024e..."
10,2021-07-29,2944.229980,0,© Copyright ICONOMICS. All Rights Reserved. Di...
11,2021-09-14,3178.573730,0,"Jakarta, TopBusiness – Holding Ultra Mikro ya..."
12,2021-09-15,3144.210938,0,JAKARTA – Holding Ultra Mikro yang melibatkan ...
13,2021-09-30,3307.434570,0,"Scan this QR or download app from: JAKARTA, iN..."
15,2022-05-09,4045.871826,0,"Koto Tangah,Liputan7.id – Pimpinan Bank BRI Un..."
16,2022-09-29,4001.215576,0,"Dorong Pelaku Usaha Bangkit, Dirut BRI Sunarso..."
17,2023-08-31,5267.768555,0,Ada delapan hal yang dikedepankan BRI untuk di...
18,2023-09-05,5338.954590,0,"Bisnis.com, JAKARTA - Direktur Utama PT Bank R..."
19,2023-09-05,5338.954590,0,Lupa Kata Sandi? Klik di Sini atau Masuk melal...
20,2023-09-05,5338.954590,0,"Jakarta, BUMN TRACK – Sebagai bagian dari foku..."
21,2023-10-26,4669.805664,0,© Copyright ICONOMICS. All Rights Reserved. Su...
22,2023-12-19,5267.768555,0,Suprajarto menjabat sebagai Direktur Utama Ban...
23,2023-12-19,5267.768555,0,"Eks Direktur Utama (Dirut) BRI, Suprajarto, m..."
24,2024-04-25,5150.000000,0,Pewarta: Uyu Septiyati LimanEditor: Nusarina Y...
25,2024-05-07,4670.000000,0,liputan6 Wakil Menteri Badan Usaha Milik Nega...
26,2024-06-25,4380.000000,0,Tina Meilina resmi ditunjuk sebagai Direktur U...
28,2024-07-25,4700.000000,0,JAKARTA - Direktur Utama PT Bank Rakyat Indone...
29,2024-07-25,4700.000000,0,Pewarta: Rizka KhaerunnisaEditor: Ahmad Buchor...
30,2024-07-25,4700.000000,0,Nyaman tanpa iklan. Langganan BisnisPro Nyaman...
31,2024-07-25,4700.000000,0,"Kita harus masih bertambah pada UMKM, tapi sa..."
32,2024-07-29,4780.000000,0,Home / Nasional / Profil Dirut Bank BRI Mediap...
34,2024-08-01,4750.000000,0,VIVA – PT. Bank Rakyat Indonesia (Persero) Tbk...
35,2024-08-01,4750.000000,0,"Scan this QR or download app from: JAKARTA, iN..."

In [8]:
df.to_csv('dataset/sea_labeled.csv', index=False)